### ISSUE TITLE
nri-oracle lockedAccounts metric is showing zero even though there are many accounts locked in the database

### ISSUE THREAD

**Issue by surengoutham1** [newrelic/nri-oracledb#192]
^^ Provide a general summary of the issue in the title above. ^^ 

## Description
lockedAccounts metric is showing zero even though there are many accounts locked in the database(Oracle19C)

## Expected Behavior
lockedAccounts metric to display appropriate count matching the number of accounts locked

**Comment by nr-ksteinbach** [comment]
Ack. We suspect the limitation to be caused by the limitation to just 3 usernames, that makes no sense to us. https://github.com/newrelic/nri-oracledb/blob/de115b2cf36e64692f6b92b11beeeb920708729b/src/metric_definitions.go#L888
We'll remove line 888 and check...

**Comment by surengoutham1** [comment]
Hi Kai Steinbach,

Thanks for taking time to troubleshoot this issue. Did you get a chance to test by removing the line you have mentioned.

And what will be the next steps. Will you be releasing a new version for this integration or you will be suggesting some workaround for the existing version.

Thanks,
Suresh

**Comment by muruganishekar** [comment]
Closing as the issue is fixed in latest release v3.9.4

**Comment by surengoutham1** [comment]
Hi Team,

We have tested v3.10.0 version of the integration and we are still facing the same issue. Even though there are multiple locked accounts, it is reporting zero.

Kindly help in fixing the same. Let us know if we need to connect over a screen sharing to check this issue.

Thanks,
Suresh
